# Generated by Django 4.2.3 on 2023-07-24 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('the_app', '0003_jobpost_slug_person_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='expiry',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='slug',
            field=models.SlugField(max_length=40, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='slug',
            field=models.SlugField(max_length=40, null=True, unique=True),
        ),
    ]
