# Generated by Django 4.2.3 on 2023-07-25 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('the_app', '0006_skills_jobpost_location_jobpost_skills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpost',
            name='skills',
            field=models.ManyToManyField(to='the_app.skills'),
        ),
    ]
