# Generated by Django 4.2.3 on 2023-07-28 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('the_app', '0007_alter_jobpost_skills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='state',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='location',
            name='zip',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
